kegiatan/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<id>[\d]+)/$', views.detaiKegiatan, name='detailed'),
    url(r'^$', views.listKegiatan, name='home'),
    url(r'^addhuman/$', views.addHuman, name='addhuman')
]

app_name = 'kegiatan'

mata_kuliah/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^remove/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
    url(r'^remove/$', views.deleteMatkul, name='remove'),
    url(r'^add/$', views.addMatkul),
    url(r'^$', views.homeMatkul, name='home'),
    url(r'^(?P<id>[\d]+)/$', views.detailedMatkul, name='detailed'),
]

app_name = 'matkul'

ppw_story1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from ppw_story4 import views as ppws4Views
from ppw_story import views as ppwViews
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^kegiatan/', include('kegiatan.urls', namespace='kegiatan')),
    url(r'^home/$', RedirectView.as_view(url='/')),
    url(r'^matkul/', include('mata_kuliah.urls', namespace='matkul')),
    url('admin/', admin.site.urls),
    url(r'^profiles1/$', ppwViews.profiles1),
    url(r'^profile/$', ppws4Views.profile),
    url(r'^myself/$', ppws4Views.myself),
    url(r'^$', ppws4Views.home),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kegiatan/models.py
from django.db import models
from django.utils import timezone

class Kegiatan(models.Model):
    name_kegiatan = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    image = models.ImageField(null=True, blank=True, upload_to='images/')

    def __str__(self):
        return '{}'.format(self.name_kegiatan)

class Human(models.Model):
    name_human = models.CharField(max_length=50)
    kegiatan = models.ManyToManyField(Kegiatan)
    time = models.TimeField(default= timezone.now)

    def __str__(self):
        return '{}'.format(self.name_human)

mata_kuliah/models.py
from django.db import models
from django.utils import timezone
from .validators import validate_sks

# Create your models here.

class Post(models.Model):
    nameMatkul = models.CharField(max_length= 50)
    teacher = models.CharField(max_length=25)
    sks = models.CharField(max_length=2,
                           validators= [validate_sks])
    desc = models.TextField(max_length=250)
    term = models.CharField(max_length=20)
    classs = models.CharField(max_length=7)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{}".format(self.nameMatkul)

ppw_story/models.py
from django.db import models

# Create your models here.

ppw_story4/models.py
from django.db import models

# Create your models here.

kegiatan/forms.py
from django import forms
from . import models

class human(forms.ModelForm):
    class Meta:
        model = models.Human
        fields = [
            'name_human',
            'kegiatan',
        ]

        labels = {
            'name_human': 'Nama',
            'kegiatan': 'Kegiatan',
        }

        widgets = {
            'name_human': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': "exampleFormControlInput1",
                    'placeholder': "contoh: Pak Pewe",
                }
            ),
        }

mata_kuliah/forms.py
from django import forms
from .models import Post

class mataKuliah(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'nameMatkul',
            'teacher',
            'sks',
            'desc',
            'term',
            'classs',
        ]

        labels = {
            'nameMatkul':'Nama Mata Kuliah',
            'teacher' : 'Nama Dosen',
            'sks' : 'Jumlah SKS',
            'desc' : 'Deskripsi',
            'term' : 'Tahun Ajaran',
            'classs' : 'Ruangan',
        }

        widgets = {
            'teacher' : forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id' : "exampleFormControlInput1",
                    'placeholder' : "contoh: Pak Pewe",
                }
            ),
            'sks': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': "exampleFormControlInput1",
                    'placeholder': "contoh: 3",
                }
            ),
            'desc': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'id': "exampleFormControlTextarea1",
                    'placeholder': "contoh: PPW is Fun",
                }
            ),
            'term': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': "exampleFormControlInput1",
                    'placeholder': "contoh: Gasal (2020/2021)",
                }
            ),
            'nameMatkul': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': "exampleFormControlInput1",
                    'placeholder': "contoh: Perancangan dan Pemrograman Web",
                }
            ),
            'classs': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': "exampleFormControlInput1",
                    'placeholder': "contoh: 4.3104",
                }
            )
        }

kegiatan/views.py
from django.shortcuts import render,redirect
from .models import Kegiatan, Human
from .forms import human
# Create your views here.

def listKegiatan(request):
    kegiatan = Kegiatan.objects.all()
    context = {
        'kegiatan': kegiatan
    }
    return render(request, 'kegiatan/listKegiatan.html', context)

def detaiKegiatan(request, id):
    kegiatan = Kegiatan.objects.get(id=id)
    human = Human.objects.filter(kegiatan__id = id)
    contects = {
        'kegiatan': kegiatan,
        'humans': human,
    }
    return render(request, 'kegiatan/detailKegiatan.html', contects)

def addHuman(request):
    human_form = human(request.POST or None)
    context = {
        'human_form': human_form,
    }
    if request.method == 'POST':
        if human_form.is_valid():
            human_form.save()
            return redirect('kegiatan:home')
    return render(request, 'kegiatan/addHuman.html', context)

mata_kuliah/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
from .forms import mataKuliah
from django.utils import timezone

def addMatkul(request):
    matkul_form = mataKuliah(request.POST or None)
    context = {
        'data_form': matkul_form,
    }
    if request.method == 'POST':
        if matkul_form.is_valid():
            matkul_form.save()
            return redirect('matkul:home')
    return render(request, 'mata_kuliah/addmatkul.html', context)

def homeMatkul(request):
    list_matkul = Post.objects.all()
    context = {
        'list_matkul': list_matkul
    }
    return render(request, 'mata_kuliah/homematkul.html', context)

def deleteMatkul(request):
    list_matkul = Post.objects.all()
    context = {
        'list_matkul': list_matkul
    }
    return render(request, 'mata_kuliah/removematkul.html', context)

def detailedMatkul(request, id):
    detail = None
    post_list = Post.objects.filter(id=id)
    if len(post_list) > 0:
        detail = post_list[0]
    else:
        detail = None
    contects = {
        'detail': detail,
        'title' : 'Matkul: ' + detail.nameMatkul
    }
    return render(request, 'mata_kuliah/detailedmatkul.html',contects)

def delete(request, delete_id):
    Post.objects.get(id=delete_id).delete()
    return redirect('matkul:remove')

ppw_story/views.py
from django.shortcuts import render

def profiles1(request):
    return render(request, 'index.html')

ppw_story4/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'Homepage.html')

def myself(request):
    return render(request, 'MySelf.html')

def profile(request):
    return render(request, 'Profile.html')

kegiatan/templates/kegiatan/addHuman.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tambah Peserta</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container" style="color: white">
        <div class= "font" style="text-align: center; margin-bottom: 50px"><h1 style="margin-top: 10px">Tambah Peserta</h1></div>
        <form method="POST" class="form-group">
            {%  csrf_token %}
            <table>
                {{human_form.as_table}}
            </table>
            <button class= "btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

kegiatan/templates/kegiatan/detailKegiatan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ kegiatan.name_kegiatan }}</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container" style="width: 75%">
        <h1 style="text-align: center; color: white"> Nama Kegiatan: {{ kegiatan.name_kegiatan }}</h1>
        <table class="table table-dark table-striped" >
            <tr><td>Deskripsi</td><td>{{ kegiatan.description }}</td></tr>
            <tr><td>Peserta</td>
                <td><ul class="list-group">
                    {% for human in humans %}
                        <li class="list-group-item" style="border: 0px; background-color: #fff0"> {{ human.name_human }} </li>
                    {% endfor %}</ul></td>
            </tr>
        </table>
        <a href="{% url 'kegiatan:home' %}"><button type="button" class="btn btn-warning">Kembali</button></a>
    </div>
</body>
</html>

kegiatan/templates/kegiatan/listKegiatan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List Kegiatan</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container">
        <div class= "font" style="text-align: center; margin-bottom: 50px"><h1 style="margin-top: 10px">List Kegiatan</h1></div>
        <div class="row" style="margin-bottom: 20px">
            <div class="card-deck">
            {% for activity in kegiatan %}
            <div class="col-sm-5 col-md-4 mb-2">
                <div class="card">
                  <img class="card-img-top" src="{{  activity.image.url }}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">{{ activity.name_kegiatan }}</h5>
                    <p class="card-text">{{ activity.description }}</p>
                    <a href="{% url 'kegiatan:detailed' activity.id %}" class="btn btn-primary" style="">detail</a>
                  </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <a href="{% url 'kegiatan:addhuman' %}"><button type="button" class="btn btn-danger" style="margin-bottom: 5px">Kuy Join</button></a>
            </div>
        </div>
    </div>
</body>
</html>

mata_kuliah/templates/mata_kuliah/addmatkul.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tambah Matkul</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container" style="color: white">
        <form method="POST" class="form-group">
            {%  csrf_token %}
            <table>
                {{data_form.as_table}}
            </table>
            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

mata_kuliah/templates/mata_kuliah/detailedmatkul.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container" style="width: 75%">
        <h1 style="text-align: center; color: white"> Mata Kuliah: {{ detail.nameMatkul }}</h1>
        <table class="table table-dark table-striped" >
            <tr><td>Nama Mata Kuliah</td><td>{{ detail.nameMatkul }}</td></tr>
            <tr><td>Dosen Pengajar</td><td>{{ detail.teacher }}</td></tr>
            <tr><td>Jumlah SKS</td><td>{{ detail.sks }}</td></tr>
            <tr><td>Deskripsi mata kuliah</td><td>{{ detail.desc }}</td></tr>
            <tr><td>Tahun Semester</td><td>{{ detail.term }}</td></tr>
            <tr><td>Ruang Kelas</td><td>{{ detail.classs }}</td></tr>
        </table>
        <a href="{% url 'matkul:home' %}"><button type="button" class="btn btn-warning">Kembali</button></a>
    </div>
</body>
</html>

mata_kuliah/templates/mata_kuliah/homematkul.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List Matkul</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container" style="width: 75%">
        <h1 style="text-align: center; color: white"> List Mata Kuliah</h1>
        <div style="overflow-y: auto">
                <table class="table table-dark table-striped">
            <thead class="thead-dark">
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Mata Kuliah</th>
                  <th scope="col">Control</th>
                </tr>
              </thead>
              <tbody>
              {% for matkul in list_matkul %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ matkul.nameMatkul }}</td>
                  <td><a href="{% url 'matkul:detailed' matkul.id %}"><button type="button" class="btn btn-light">Detail</button></a></td>
                </tr>
            {% endfor %}
              </tbody>
        </table>
        </div>

    <a href="/matkul/add"><button type="button" class="btn btn-primary">Tambah</button></a>
    <a href="{% url 'matkul:remove' %}"><button type="button" class="btn btn-danger">Hapus</button></a>
    </div>
</body>
</html>

mata_kuliah/templates/mata_kuliah/removematkul.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hapus Matkul</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="container" style="width: 75%">
        <h1 style="text-align: center; color: white"> List Mata Kuliah</h1>
        <div style="overflow-y: auto">
            <table class="table table-dark table-striped">
        <thead class="thead-dark">
            <tr>
              <th scope="col">No</th>
              <th scope="col">Mata Kuliah</th>
              <th scope="col">Control</th>
            </tr>
          </thead>
          <tbody>
          {% for matkul in list_matkul %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ matkul.nameMatkul }}</td>
              <td><a href="{% url 'matkul:delete' matkul.id %}"><button type="button" class="btn btn-danger">Hapus</button></a></td>
            </tr>
        {% endfor %}
          </tbody>
    </table>
        </div>
    <a href="{% url 'matkul:home' %}"><button type="button" class="btn btn-warning">Selesai</button></a>
    </div>
</body>
</html>

templates/Homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Homepage</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
      {% include 'base.html' %}
      <div class="fixed-intro font" id="font-intro">
          <div>
              <p>Hallo nama saya</p>
              <p><span id="firstname">Mochammad</span> <span id="lastname">Naufal Rizki</span></p>
              <p>Welcome to my Website :)</p>
          </div>
          <div>
              <img class="profile" src="{% static "svg/profile.svg" %}" id="img-profile-home">
          </div>
          <div>
              <a href="/profile"><button type="button" class="btn btn-primary">Profile</button></a>
              <a href="/myself"><button type="button" class="btn btn-primary">My Self</button></a>
          </div>
      </div>
    </body>
</html>

templates/MySelf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Myself</title>
</head>
<body>
    {% include 'base.html' %}
    <div class="font fixmyself" id="font-intro">
        <img class="profile" id="img-profile-myself" src="{% static "svg/profile.svg" %}">
        <img class="garis" src="{% static "svg/a - ms.svg" %}">
	    <div class="mydesc">
            <p>Halo, saya Mochammad Naufal Rizki  biasa dipanggil naufal.
                Saya merupakan seorang mahasiswa Fasilkom Universitas Indonesia.
                Saya memiliki kegemaran bermain game, baca komik dan membaca isu-isu mengenai perkembangan teknologi.
                Saya merupakan seorang yang telaten dan selalu fokus terhadap suatu pekerjaan yang masih belum selesai.
                Saya memiliki ambisi menjadi orang yang ahli di bidang IT dan bisa menciptakan suatu aplikasi
                yang sangat berguna bagi masyarakat.</p>
        </div>
    </div>
</body>
</html>

templates/Profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
     {% include 'base.html' %}
    <div class="fixed-profile font">
        <h1 id="h1" style="text-align: center">Profil Saya</h1>
        <img class="profile" id="img-profile-profile" src="{% static "svg/profile.svg"%}">
        <div class="bio" id="font-profile">
            <img class="kotak" src="{% static "svg/kotak.svg" %}">
            <div class="q">
                <p>Nama</p> <p>Tempat, Tanggal Lahir</p> <p>NPM</p> <p>Angkatan</p> <p>Hobi</p>
                <p>Riwayat Penddidikan</p> <p><br></p> <p>Sosial Media</p>
            </div>
            <div class="eq">
                <p>:</p><p>:</p><p>:</p><p>:</p><p>:</p><p>:</p> <p><br></p><p>:</p>
            </div>
            <div class="ans">
                <p>Mochammad Naufal Rizki</p>
                <p>Sukabumi, 05 April 2001</p>
                <p>1906299010</p>
                <p>2019</p>
                <p>Bermain Game, Baca Komik</p>
                <p>SDN 1 Pasirhalang</p>
                <p>SMPN 1 Sukaraja</p>
                <p>SMAN 1 Sukabumi</p>
                <p>085155100326</p>
                <p>naxtamvan69</p>
            </div>
        </div>
    </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&family=Rajdhani">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="{% static "css/test.css" %}" rel="stylesheet" type="text/css">
</head>

<body>
<div>
    <header>
         <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <img src="{% static "svg/darkcat.svg" %}" style="width: 50px; height: 50px;">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="/profile">Profile</a>
              <a class="nav-item nav-link" href="/myself">My Self</a>
              <a class="nav-item nav-link" href="/profiles1">Profile S1</a>
                <a class="nav-item nav-link" href="/matkul">Mata Kuliah</a>
                <a class="nav-item nav-link" href="/kegiatan">Kegiatan</a>
            </div>
          </div>
        </nav>
    </header>
    </div>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Story 1</title>
</head>
<body class = font>
    {% include 'base.html' %}
    <center>
        <h1>Profil Saya</h1>
        <img src="{% static "img/profile.jpg" %}" alt="" height="301" width="200" class="center">
        <table border="1" >
            <p></p>
            <tr><td>Nama :</td><td>Mochammad Naufal Rizki</td></tr>
            <tr><td>NPM :</td><td>1906299010</td></tr>
            <tr><td>Angkatan :</td><td>2019</td></tr>
            <tr><td>Hobi :</td><td>Bermain gim, baca komik</td></tr>
            <tr><td>Deskripsi Tentang Saya :</td><td>Saya orangnya agak cuek terhadap lingkungan sekitar</td></tr>
            <tr><td>Tempat Kuliah :</td><td>Universitas Indonesia</td></tr>
            <tr>
                <td rowspan="3">Riwayat Pendidikan :</td>
                <td>SD : SDN 1 Pasirhalang</td>
            </tr>
            <tr><td>SMP : SMPN 1 Sukaraja</td>
            <tr><td>SMA : SMAN 1 Sukabumi</td>
            <tr>
                <td rowspan="2">Sosial Media :</td>
                <td>Line : naxtamvan69</td>
            </tr>
            <tr><td>WA : 085155100326</td>
        </table>
    </center>
</body>
</html>